// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmVUtSenFfQZyzPHypTNurX9bzbVpSRIM',
    appId: '1:49302266564:web:1a458b4386ded152e51f91',
    messagingSenderId: '49302266564',
    projectId: 'esuit-84fd2',
    authDomain: 'esuit-84fd2.firebaseapp.com',
    storageBucket: 'esuit-84fd2.appspot.com',
    measurementId: 'G-Q1RJ23Z8J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiA4Ks62Fk4W0vj80bz1EkDiJpVL1oqEI',
    appId: '1:49302266564:android:7447514c72021d30e51f91',
    messagingSenderId: '49302266564',
    projectId: 'esuit-84fd2',
    storageBucket: 'esuit-84fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYiTXpbVhD6qQ6T0Oihy1e8CT1wkcpLLY',
    appId: '1:49302266564:ios:4cfca77e872178dce51f91',
    messagingSenderId: '49302266564',
    projectId: 'esuit-84fd2',
    storageBucket: 'esuit-84fd2.appspot.com',
    androidClientId: '49302266564-eq2ufeb8b12cg07mmkebkmpjndumb4fi.apps.googleusercontent.com',
    iosClientId: '49302266564-3di9t8a2gnpne8b6urdtu9q6mrjrovh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.vasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYiTXpbVhD6qQ6T0Oihy1e8CT1wkcpLLY',
    appId: '1:49302266564:ios:3a3c085b1bdbf4ece51f91',
    messagingSenderId: '49302266564',
    projectId: 'esuit-84fd2',
    storageBucket: 'esuit-84fd2.appspot.com',
    androidClientId: '49302266564-eq2ufeb8b12cg07mmkebkmpjndumb4fi.apps.googleusercontent.com',
    iosClientId: '49302266564-hcet3todla6aam8o2r1ooahatulgqncd.apps.googleusercontent.com',
    iosBundleId: 'com.example.vasa.RunnerTests',
  );
}
